name: diffsbdd
channels:
  - pytorch      # put first or second, but before conda-forge
  - pyg
  - conda-forge
  - defaults     # (drop “nvidia” entirely on Windows)

dependencies:
  - python=3.10
  # - pytorch=2.0.*=*cuda118*   # explicit GPU build
  # - torchvision=0.15.*
  # - torchaudio=2.0.*
  # - pytorch-cuda=11.8
  - rdkit=2022.03.2
  - openbabel=3.1.1
  - numpy=1.26.4
  - scipy=1.13.1
  - pandas=2.2.2
  - imageio=2.21.2
  - networkx=3.3
  # - pytorch-lightning=1.8.4
  # - pytorch-scatter=2.1.1
  # - torchmetrics=1.4.2
  - seaborn=0.13.2
  - tqdm
  - pyyaml
  - protobuf=3.20.*
  - pip
  - pip:
      - wandb==0.13.1         # easiest via pip
