run_name: 'SE3-cond-full_lighermodel1'
logdir: './logs'

wandb_params:
  mode: 'online' # disabled, offline, online
  entity: 'umich_med'
  group: 'full_atom_cond'

dataset: 'bindingmoad'
datadir: 'C:\Users\Dorzhey\OneDrive\Desktop\grafton\DiffSBDD\pdbbind_demo_v2021\demo\processed_pdbbind_phys_features'

enable_progress_bar: False
num_sanity_val_steps: 0

mode: 'pocket_conditioning'
pocket_representation: 'full-atom'
virtual_nodes: False

batch_size: 2
lr: 5.0e-4
n_epochs: 1000
num_workers: 0
gpus: 1
clip_grad: True
augment_rotation: False
augment_noise: 0.0

auxiliary_loss: False
loss_params:
  max_weight: 0.001
  schedule: 'linear'
  clamp_lj: 3.0

egnn_params:
  device: 'cuda'
  edge_cutoff_ligand: null
  edge_cutoff_pocket: 4.0
  edge_cutoff_interaction: 7.0
  reflection_equivariant: False
  edge_embedding_dim: 8
  joint_nf: 16
  hidden_nf: 32
  n_layers: 3
  attention: True
  tanh: True
  norm_constant: 1
  inv_sublayers: 1
  sin_embedding: False
  aggregation_method: 'sum'
  normalization_factor: 100 # used if aggregation_method='sum'

diffusion_params:
  diffusion_steps: 100
  diffusion_noise_schedule: 'polynomial_2' # learned, cosine
  diffusion_noise_precision: 1.0e-5
  diffusion_loss_type: 'l2' # vlb, l2
  normalize_factors: [1, 4] # [x, h]

eval_epochs: 30
visualize_sample_epoch: 0
visualize_chain_epoch: 0

eval_params:
  n_eval_samples: 100
  eval_batch_size: 10
  smiles_file: 'C:\Users\Dorzhey\OneDrive\Desktop\grafton\DiffSBDD\pdbbind_demo_v2021\demo\processed_pdbbind_noH_full\train_smiles.npy'
  n_visualize_samples: 0
  keep_frames: 100